version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "web"
    restart: "always"
    volumes:
      - type: bind
        source: ./code
        target: /code/
    env_file:
      - ./.env
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: postgres:14.3-alpine
    restart: "always"
    ports:
      - "5432:5432"
    container_name: "db"
    volumes:
      - /data:/var/lib/postgresql/data
    env_file:
      - ./.env


  nginx:
    build:
      context: ./nginx/.
      dockerfile: Dockerfile
    container_name: "nginx"
    restart: "always"
    volumes:
      - type: bind
        source: ./code/static/
        target: /code/static/

      - type: bind
        source: ./code/media/
        target: /code/media/
    ports:
      - "80:80"
    depends_on:
      - web