# Generated by Django 4.0.4 on 2022-05-21 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('content', models.CharField(max_length=300, verbose_name='Content')),
                ('description', models.TextField(verbose_name='Description')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='post_images', verbose_name='Post Image')),
                ('visited', models.PositiveIntegerField(blank=True, default=0, verbose_name='Visited')),
                ('allow_comment', models.BooleanField(blank=True, default=True, verbose_name='Allow Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated ')),
                ('category', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Post.category', verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-created_at'],
            },
        ),
    ]
