# Generated by Django 4.0.4 on 2022-06-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_reply_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply_comment',
            old_name='author',
            new_name='user',
        ),
    ]
